### ISSUE TITLE
Giddyup nil pointer dereference.

### ISSUE THREAD

**Issue by SamMousa** [rancher/giddyup#25]
When running giddyup outside of rancher, some commands fail in an extreme way:
````

$ docker run rancher/giddyup:v0.16.0 giddyup ip stringify
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5a9573]

goroutine 1 [running]:
panic(0x7e4840, 0xc820010070)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/rancher/giddyup/vendor/github.com/urfave/cli.HandleAction.func1(0xc8200e15a8)
	/go/src/github.com/rancher/giddyup/vendor/github.com/urfave/cli/app.go:472 +0x417
panic(0x7e4840, 0xc820010070)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/rancher/giddyup/vendor/github.com/rancher/go-rancher-metadata/metadata.(*Client).SendRequest(0x0, 0x86afc0, 0xf, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/giddyup/vendor/github.com/rancher/go-rancher-metadata/metadata/metadata.go:30 +0x93
github.com/rancher/giddyup/vendor/github.com/rancher/go-rancher-metadata/metadata.(*Client).GetSelfContainer(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/giddyup/vendor/github.com/rancher/go-rancher-metadata/metadata/metadata.go:72 +0x66
github.com/rancher/giddyup/app.getSelfStackServiceName(0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/giddyup/app/ip.go:203 +0x75
github.com/rancher/giddyup/app.ipStringifyMetadata(0xc82009a500, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/giddyup/app/ip.go:169 +0x61f
github.com/rancher/giddyup/app.ipStringifyAction(0xc82009a500, 0x0, 0x0)
	/go/src/github.com/rancher/giddyup/app/ip.go:92 +0x314
reflect.Value.call(0x74ef80, 0x920018, 0x13, 0x864480, 0x4, 0xc8200e1508, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x74ef80, 0x920018, 0x13, 0xc8200e1508, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0xb1
github.com/rancher/giddyup/vendor/github.com/urfave/cli.HandleAction(0x74ef80, 0x920018, 0xc82009a500, 0x0, 0x0)
	/go/src/github.com/rancher/giddyup/vendor/github.com/urfave/cli/app.go:481 +0x2ee
github.com/rancher/giddyup/vendor/github.com/urfave/cli.Command.Run(0x877210, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8bb080, 0x1b, 0x0, ...)
	/go/src/github.com/rancher/giddyup/vendor/github.com/urfave/cli/command.go:186 +0x1301
github.com/rancher/giddyup/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc820001200, 0xc82009a280, 0x0, 0x0)
	/go/src/github.com/rancher/giddyup/vendor/github.com/urfave/cli/app.go:355 +0x10d5
github.com/rancher/giddyup/vendor/github.com/urfave/cli.Command.startApp(0x8670e8, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8a9700, 0x12, 0x0, ...)
	/go/src/github.com/rancher/giddyup/vendor/github.com/urfave/cli/command.go:273 +0xa30
github.com/rancher/giddyup/vendor/github.com/urfave/cli.Command.Run(0x8670e8, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8a9700, 0x12, 0x0, ...)
	/go/src/github.com/rancher/giddyup/vendor/github.com/urfave/cli/command.go:74 +0x7b
github.com/rancher/giddyup/vendor/github.com/urfave/cli.(*App).Run(0xc820001080, 0xc82000a0f0, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/rancher/giddyup/vendor/github.com/urfave/cli/app.go:235 +0xa9c
main.main()
	/go/src/github.com/rancher/giddyup/main.go:26 +0x832

````

I realize running `giddyup` outside rancher makes no sense, still I think it should fail more gracefully then this!

**Comment by cloudnautique** [comment]
Indeed. A help message seems appropriate.

**Comment by SamMousa** [comment]
It seems this no longer happens in 0.19
